### ISSUE TITLE
Add support for downloading id's and alternative video version

### ISSUE THREAD

**Issue by notcammy** [sdushantha/SnapStory#1]
I actually played with this API endpoint a few days ago, I noticed that it also accepts certain id's. 

Single story
https://story.snapchat.com/s/s:lmRcFPGGRPOj2uHCIQ5Fig

Events
https://story.snapchat.com/s/3g2zLTLJSzKk0uA-cR2aDQ

Also, some `mediaUrl` values are urls ending in `embedded.mp4`. If you change this part of the url to `media.mp4` it will return the same story but without added effects like captions or animations. 
I think this is only with videos, haven't done enough research to be sure.

**Comment by sdushantha** [comment]
So do you want to be able to do something like this?

Single story
```bash
$ python3 snapstory.py -s lmRcFPGGRPOj2uHCIQ5Fig
# Where the -s flag is for single storys.
```

Events
```bash
$ python3 snapstory.py -e 3g2zLTLJSzKk0uA-cR2aDQ
# Where the -e flag is for events
```

I looked in to the ```embedded.mp4``` ending. Should we add a flag which allows the user to do decide if they want to remove the effects? Im thinking of a flag like ```-c``` for clean. Do you have an idea of what flag we should have?

By the way, thanks for sharing your research with me. If you come by more interesting stuff, please let me know because my plan is to try to make an unofficial SnapChat API in the future. :smile:

**Comment by notcammy** [comment]
I don't think any flags for the id's. They work the same way as if you've entered and username, and since id's have more characters than the maximum allowed Snapchat username length (> 15) you can assume the given argument is an id if it's longer than 15 characters and the response 
 is not an error.

As for the effects I had my own version of the script download both `embedded` and `media` by default, but using a flag also works.

**Comment by notcammy** [comment]
I've checked this with a few different Snapchat users and it seems the endpoint no longer includes any images in the JSON response.

**Comment by sdushantha** [comment]
Yea I see. I just checked it. I will remove the code which downloads the images today. Or I guess it would be better to just comment it out because SnapChat might bring back the images. 

----
BTW, did you hear that some part  off SnapChats source code got leaked?

**Comment by notcammy** [comment]
Yeah there are some forks of it on Gitlab, but I don't see much in there that would be useful if you're trying to make an unofficial API.

**Comment by sdushantha** [comment]
Added support for ids and single stories
