### ISSUE TITLE
UnboundLocalError: local variable 'filetype' referenced before assignment

### ISSUE THREAD

**Issue by bakixmax** [sdushantha/SnapStory#3]
![Screenshot from 2020-09-30 03-33-18](https://user-images.githubusercontent.com/64330423/94630390-48090000-02ce-11eb-8990-3dfb4e119b49.png)
a@A-VirtualBox:~/Desktop$ cd SnapStory
a@A-VirtualBox:~/Desktop/SnapStory$ python3 snapstory.py alqassar_show
[+] Valid story
[+] Fetched data
[!] Downloading from سليمان القصار 🇰🇼 ⭐ (alqassar_show)
Traceback (most recent call last):
  File "snapstory.py", line 154, in <module>
    main()
  File "snapstory.py", line 148, in main
    download(args.username)
  File "snapstory.py", line 95, in download
    dir_name = username+"/"+filetype+"/"
UnboundLocalError: local variable 'filetype' referenced before assignment
a@A-VirtualBox:~/Desktop/SnapStory$

**Comment by sdushantha** [comment]
This script no longer works because Snapchat keeps changing their API and it is difficult to keep up with them
